location /storage/maps/ {
    alias /path/to/project/storage/app/public/maps/;

    add_header Accept-Ranges bytes always;
    add_header Access-Control-Allow-Origin * always;

    types {
        application/octet-stream pmtiles;
    }

    if ($request_method = 'OPTIONS') {
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
        add_header Access-Control-Allow-Headers 'Range, Content-Type, Content-Length';
        add_header Content-Length 0;
        return 204;
    }
}
