<template>
  <AppLayout>
    <div class="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm font-medium text-[#EDD330]">Inventaris Ambalan</p><h1 class="mt-1 text-2xl font-bold text-[#f0ead8]">Barang dan Aset</h1><p class="mt-1 text-sm text-[#8fa06a]">Pantau ketersediaan, kondisi, dan riwayat peminjaman barang.</p></div><button v-if="canManage" @click="showCreate = true" class="inline-flex w-fit items-center rounded-lg bg-gradient-to-r from-[#A7B92A] to-[#6F9435] px-4 py-2 text-sm font-semibold text-white">+ Tambah barang</button></div>
    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><article v-for="item in items.data" :key="item.id" class="rounded-2xl border border-[#6F9435] bg-[#335233] p-5 shadow-sm border-[#6F9435]"><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-semibold uppercase tracking-wide text-[#EDD330]'">{{ item.kode_barang }}</p><h2 class="mt-1 text-lg font-semibold text-[#f0ead8]">{{ item.nama_barang }}</h2></div><span class="rounded-full px-2.5 py-1 text-xs" :class="item.status_pinjam === 'Tersedia' ? 'bg-[#A7B92A]/20 text-[#A7B92A]' : 'bg-[#EDD330]/20 text-[#EDD330]'">{{ item.status_pinjam }}</span></div><div class="mt-5 grid grid-cols-3 gap-2 text-center"><div class="rounded-xl bg-[#263D26] p-3"><p class="text-xl font-bold">{{ item.jumlah }}</p><p class="mt-1 text-[11px] text-[#8fa06a]">Jumlah</p></div><div class="rounded-xl bg-[#263D26] p-3"><p class="text-xl font-bold">{{ item.kondisi }}</p><p class="mt-1 text-[11px] text-[#8fa06a]">Kondisi</p></div><div class="rounded-xl bg-[#263D26] p-3"><p class="text-xl font-bold">{{ item.loans_count }}</p><p class="mt-1 text-[11px] text-[#8fa06a]">Pinjam</p></div></div><div class="mt-4 flex flex-wrap gap-2"><button v-if="canManage" @click="openLoan(item)" class="rounded-lg bg-gradient-to-r from-[#A7B92A] to-[#6F9435] px-3 py-2 text-xs font-semibold text-white">Pinjam</button><button v-if="canManage" @click="selected = item; showAdjust = true" class="rounded-lg border border-[#6F9435] px-3 py-2 text-xs font-semibold text-[#d4dc9a]">Sesuaikan stok</button></div></article></div>
    <Modal v-if="showCreate && canManage" title="Tambah inventaris" @close="showCreate = false"><form @submit.prevent="form.post('/inventory', { onSuccess: () => showCreate = false })" class="grid gap-3 sm:grid-cols-2"><label class="block"><span class="text-xs font-medium">Kode barang</span><input v-model="form.kode_barang" required class="mt-1 w-full rounded-lg border border-[#6F9435] bg-[#335233] px-3 py-2 text-sm" /></label><label class="block"><span class="text-xs font-medium">Nama barang</span><input v-model="form.nama_barang" required class="mt-1 w-full rounded-lg border border-[#6F9435] bg-[#335233] px-3 py-2 text-sm" /></label><label class="block"><span class="text-xs font-medium">Jenis</span><select v-model="form.jenis" class="mt-1 w-full rounded-lg border border-[#6F9435] bg-[#335233] px-3 py-2 text-sm"><option>Aset</option><option>Stok</option></select></label><label class="block"><span class="text-xs font-medium">Satuan</span><input v-model="form.satuan" value="Unit" class="mt-1 w-full rounded-lg border border-[#6F9435] bg-[#335233] px-3 py-2 text-sm" /></label><label class="block"><span class="text-xs font-medium">Jumlah</span><input v-model="form.jumlah" type="number" min="0" required class="mt-1 w-full rounded-lg border border-[#6F9435] bg-[#335233] px-3 py-2 text-sm" /></label><button class="rounded-lg bg-gradient-to-r from-[#A7B92A] to-[#6F9435] px-4 py-2 text-sm font-semibold text-white sm:col-span-2">Simpan barang</button></form></Modal>
    <Modal v-if="showLoan && selected && canManage" title="Catat peminjaman" @close="showLoan = false"><form @submit.prevent="loan.post('/inventory-loans', { onSuccess: () => showLoan = false })" class="grid gap-3"><input type="hidden" v-model="loan.inventory_id" /><label class="block"><span class="text-xs font-medium">Peminjam</span><input v-model="loan.peminjam_nama" required class="mt-1 w-full rounded-lg border border-[#6F9435] bg-[#335233] px-3 py-2 text-sm" /></label><label class="block"><span class="text-xs font-medium">Tanggal pinjam</span><input v-model="loan.tgl_pinjam" type="date" required class="mt-1 w-full rounded-lg border border-[#6F9435] bg-[#335233] px-3 py-2 text-sm" /></label><button class="rounded-lg bg-gradient-to-r from-[#A7B92A] to-[#6F9435] px-4 py-2 text-sm font-semibold text-white">Simpan peminjaman</button></form></Modal>
    <Modal v-if="showAdjust && selected && canManage" title="Sesuaikan stok" @close="showAdjust = false"><form @submit.prevent="adjust.post('/inventory-adjustments', { onSuccess: () => showAdjust = false })" class="grid gap-3"><input type="hidden" v-model="adjust.inventory_id" /><label class="block"><span class="text-xs font-medium">Selisih stok</span><input v-model="adjust.jumlah" type="number" required class="mt-1 w-full rounded-lg border border-[#6F9435] bg-[#335233] px-3 py-2 text-sm" /></label><label class="block"><span class="text-xs font-medium">Catatan</span><textarea v-model="adjust.catatan" required rows="3" class="mt-1 w-full rounded-lg border border-[#6F9435] px-3 py-2 text-sm"></textarea></label><button class="rounded-lg bg-gradient-to-r from-[#A7B92A] to-[#6F9435] px-4 py-2 text-sm font-semibold text-white">Simpan penyesuaian</button></form></Modal>
  </AppLayout>
</template>
<script setup>
import { computed, ref } from 'vue';
import { useForm, usePage } from '@inertiajs/vue3';
import AppLayout from '@/Components/AppLayout.vue';
import SkeletonLoader from '@/Components/SkeletonLoader.vue';
import Modal from '@/Components/Modal.vue';
defineProps({ items: Object });
const page = usePage();
const canManage = computed(() => {
  const role = page.props.auth?.user?.role;
  return role === 'Admin' || role === 'Pembina' || role === 'Pengurus';
});
const showCreate = ref(false); const showLoan = ref(false); const showAdjust = ref(false); const selected = ref(null);
const form = useForm({ kode_barang: '', nama_barang: '', jenis: 'Aset', satuan: 'Unit', jumlah: 0 });
const loan = useForm({ inventory_id: '', peminjam_nama: '', tgl_pinjam: new Date().toISOString().slice(0, 10) });
const adjust = useForm({ inventory_id: '', jumlah: 0, catatan: '' });
function openLoan(item) { selected.value = item; loan.inventory_id = String(item.id); loan.peminjam_nama = ''; loan.tgl_pinjam = new Date().toISOString().slice(0, 10); showLoan.value = true; }
</script>

